# -*- coding: utf-8 -*-
"""Verificador de cartão de crédito

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmOC_TZrCdBkn9vqHRZxhpSgjp5dY4fa
"""

soma_pares = 0
soma_impares = 0
total = 0

numero_cartao = input('Digite número do cartão de crédito')
numero_cartao = numero_cartao.replace('-','')
numero_cartao = numero_cartao.replace(' ','')
numero_cartao = numero_cartao [::-1]

for numero in numero_cartao[::2]:
    soma_pares += int(numero)
for numero in numero_cartao[1::2]:
  numero = int(numero)*2
  if numero >=10:
      soma_impares += (1+(numero % 10))
  else:
    soma_impares +=numero
total = soma_pares + soma_impares
if total % 10 == 0:
  print('Cartão Válido')
else:
  print('Cartão inválido')

bandeira = ['VISA', 'MASTERCARD', 'ELO', 'AMEX']

while True:
    bandeira_cartao = input('Selecione a bandeira do seu cartão de crédito: ').upper()

    if bandeira_cartao in bandeira:
        print(f'Bandeira selecionada {bandeira_cartao}')
        break
    else:
        print('Selecione uma bandeira válida')

